spring.application.name=payment-service
server.port=8081
spring.kafka.bootstrap-servers=localhost:9094

#key used to determine which partition it has to go to
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

#actual message data
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.value.default.type=com.kafka.learning.events.OrderCreatedEvent

#ignores headers sent my Kafka
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.consumer.group-id=payment-group

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# Resilience4j Circuit Breaker
# ==============================

#create circuit breaker named paymentGateway
resilience4j.circuitbreaker.instances.paymentGateway.register-health-indicator=true

#Number of recent calls used to calculate the failure rate
resilience4j.circuitbreaker.instances.paymentGateway.sliding-window-size=5 

#Wait until at least 5 calls are made before evaluating the failure rate
resilience4j.circuitbreaker.instances.paymentGateway.minimum-number-of-calls=5

#Open Circuit when this threshold crosses (>50% of failure)
resilience4j.circuitbreaker.instances.paymentGateway.failure-rate-threshold=50

#Duration in which circuit should be kept open
resilience4j.circuitbreaker.instances.paymentGateway.wait-duration-in-open-state=10s

#instead of opening everything again, allows only 2 reqs, if both succeeds close circuit, if even one fail open circuit again
resilience4j.circuitbreaker.instances.paymentGateway.permitted-number-of-calls-in-half-open-state=2

#automatic transition from open to half open to test system.
resilience4j.circuitbreaker.instances.paymentGateway.automatic-transition-from-open-to-half-open-enabled=true


#Failures > 50%
#      │
#      ▼
#┌─────────────┐
#│   CLOSED    │
#└─────────────┘
#      │
#      ▼
#┌─────────────┐
#│    OPEN     │
#└─────────────┘
#  Wait 10 sec
#        │
#        ▼
#┌──────────────────┐
#│    HALF OPEN     │
#└──────────────────┘
# 2 successful calls?
# │            │
# Yes          No
# │            │
# ▼            ▼
# CLOSED         OPEN


# ==============================
# Resilience4j Retry
# ==============================

#1 original call + 2 retries incase of failure
resilience4j.retry.instances.paymentGateway.max-attempts=3

#wait half a second before first retry
resilience4j.retry.instances.paymentGateway.wait-duration=500ms

#Each retry waits longer than the previous one.
resilience4j.retry.instances.paymentGateway.enable-exponential-backoff=true

#wait time multiplied by 2 after every retry attempt
resilience4j.retry.instances.paymentGateway.exponential-backoff-multiplier=2